version: '3'
services:
  bee:
    image: ethersphere/bee:1.0.0
    restart: on-failure
    environment:
      - BEE_API_ADDR
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE=/dnsaddr/testnet.ethswarm.org
      - BEE_BOOTNODE_MODE
      - BEE_CLEF_SIGNER_ENABLE=false
      - BEE_CLEF_SIGNER_ENDPOINT
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=30000000
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID=10
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD=123456
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT=https://goerli.infura.io/v3/YOUR_KEY_HERE
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY=5
      - BEE_WELCOME_MESSAGE
      - BEE_MAINNET=false
    ports:
      - "${API_ADDR:-1633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-1635}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /home/bee-data:/home/bee/.bee
    command: start

  nectar:
    image: bzznectar/nectar:v0.5.5
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      - NCTR_DEBUG_API_ADDR=:9000
      - NCTR_BEE_DEBUG_API=172.17.0.1:1635
      - NCTR_DATA_DIR=/root/.nectar
      - NCTR_MAINNET=false
      - NCTR_NETWORK_ID=10
      - NCTR_PASSWORD=123456
      - NCTR_SWAP_ENDPOINT=https://goerli.infura.io/v3/YOUR_KEY_HERE
      - NCTR_HARVEST_GAS=7000000
      - NCTR_SWAP_INITIAL_DEPOSIT=7000000


    command: start
    volumes:
      - /home/nectar-data:/root/.nectar
    depends_on:
      - bee
